apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: api-cinemaec
spec:
  template:
    metadata:
      annotations:
        # Increase startup probe timeout to 10 minutes for migrations
        run.googleapis.com/startup-probe-timeout-seconds: '600'
        run.googleapis.com/startup-probe-period-seconds: '30'
        run.googleapis.com/startup-probe-failure-threshold: '20'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: us-east4-docker.pkg.dev/cinema-ec/cinema-ec/backend:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: '2'
            memory: 2Gi
        startupProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 0
          timeoutSeconds: 10
          periodSeconds: 30
          failureThreshold: 20
