apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: api-cinemaec
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        # Cloud Run startup probe configuration
        # Total timeout: periodSeconds × failureThreshold = 30 × 20 = 600s (10 min)
        run.googleapis.com/startup-probe-timeout-seconds: '600'
        run.googleapis.com/startup-probe-period-seconds: '30'
        run.googleapis.com/startup-probe-failure-threshold: '20'
        # CPU always allocated (required for migrations)
        run.googleapis.com/cpu-throttling: 'false'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: us-central1-docker.pkg.dev/cinema-ec/docker-repo/api-cinemaec:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: NODE_ENV
          value: production
        - name: PORT
          value: '8080'
        resources:
          limits:
            cpu: '2'
            memory: 2Gi
          requests:
            cpu: '1'
            memory: 512Mi
        startupProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 0
          timeoutSeconds: 10
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 20
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
